### ISSUE TITLE
Comment needs to be confirmed

### ISSUE THREAD

**Issue by lcrowley** [EricEdwardBryant/rothfreezer#5]
For lines 222 and 323 in MATa-cispt-384-hb, strain_collection strain_comment has NA-NA-#, formatting and content need to be confirmed.

**Comment by EricEdwardBryant** [comment]
Ah yes, I see the issue. There may be some missing data in one a keyfile that I used to generate those comments. I'll have a look.

**Comment by EricEdwardBryant** [comment]
The issues with rec5948 (MATa vma10::KanMX) and rec7160 (MATa mms4::KanMX) are only in `inst/db/MATa-cispt-384-hb.csv`. I can't seem to find the source of the missing values that are in the strain comments column for this file. The strains table isn't missing strain names for these records. 

@breid381 any idea where the missing values came from?

Anyhow, the NAs have been fixed in 8d7216fb805acea7e9ebc98515df42837b1c7bf4
